### ISSUE TITLE
Invalid zerops.yaml throws an error but exits with 0

### ISSUE THREAD

**Issue by kracas** [zeropsio/zcli#159]
If zerops.yaml is invalid, zcli throws an error, but exits with code 0. If this happens in CI/CD, the pipeline does not throw an error as zcli exits with 0. zcli should preferably exit with 1 or anything else more specific in such situation. 
zcli v1.0.21

**Comment by MichalSalon** [comment]
Hello, this should be fixed in the latest release [v1.0.22](https://github.com/zeropsio/zcli/releases/tag/v1.0.22)
